<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4bXky9I\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4bXky9I/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4bXky9I.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4bXky9I\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container4bXky9I\srcDevDebugProjectContainer(array(
    'container.build_hash' => '4bXky9I',
    'container.build_id' => 'a8f2183e',
    'container.build_time' => 1538484619,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4bXky9I');
