<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU3x0RxH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU3x0RxH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerU3x0RxH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerU3x0RxH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerU3x0RxH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'U3x0RxH',
    'container.build_id' => '920eb488',
    'container.build_time' => 1537888506,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerU3x0RxH');
